---
#
# ansistrano after update code tasks
#

- name: be sure install dir created
  become: yes
  file:
    path: "{{ ansistrano_deploy_to }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    recurse: true
    mode: 0755

- name: be sure yarn for frontend
  become: yes
  become_user: "{{ user }}"
  command: yarn
  args:
    chdir: "{{ ansistrano_deploy_to }}/releases/{{ ansistrano_release_version }}/frontend"

- name: be sure yarn build for frontend
  become: yes
  become_user: "{{ user }}"
  command: yarn build
  args:
    chdir: "{{ ansistrano_deploy_to }}/releases/{{ ansistrano_release_version }}/frontend"

- name: be sure symboilc link to dist
  become: yes
  become_user: "{{ user }}"
  file:
    state: link
    src: ../frontend/dist
    dest: "{{ ansistrano_deploy_to }}/releases/{{ ansistrano_release_version }}/backend/dist"

- name: be sure yarn for backend
  become: yes
  become_user: "{{ user }}"
  command: yarn
  args:
    chdir: "{{ ansistrano_deploy_to }}/releases/{{ ansistrano_release_version }}/backend"

- name: be sure systemd script copied
  template:
    src: ../templates/nodejs.service.j2
    dest: /etc/systemd/system/{{ product_name }}.service
    owner: root
    group: root
    mode: 0644

#
# ToDo
# 1) copy to service
# 2) systemd enabled
#
