## from galaxy https://galaxy.ansible.com/
- src: ansistrano.deploy
- src: ansistrano.rollback

#
# - src: nickhammond.logrotate

# from github

# see
# https://qiita.com/kotarella1110/items/212dceee3e56fbffddd1
