---
#
# Initialize
#

- name: Initialize block
  block:
    - name: be sure minio gorup created
      group:
        name: "{{ minio_group }}"

    - name: be sure minio user created
      user:
        name: "{{ minio_user }}"
        group: "{{ minio_group }}"
        create_home: no

    - name: be sure directories created
      file: 
        path: "{{ item }}"
        state: directory
        owner: "{{ minio_user }}"
        group: "{{ minio_group }}"
        mode: 0750
      with_items:
        - "{{ minio_root_dir}}"
        - "{{ minio_root_dir}}/bin"
        - "{{ minio_root_dir}}/config"
        - "{{ minio_root_dir}}/data"

#
# Get facts
#

- name: Get facts
  block:
    - name: gets fact of the minio executable file
      stat:
        path: "{{ minio_root_dir }}/bin/minio"
      register: minio_file
#
# main routine
#
- name: main routine
  block:
    - name: gets minio server
      get_url:
        url: https://dl.minio.io/server/minio/release/linux-amd64/minio
        dest: "{{ minio_root_dir }}/bin/minio"
        owner: "{{ minio_user }}"
        group: "{{ minio_group }}"
        mode: 0750
      when: minio_file.stat.exists == false

    - name: be sure configuration to /etc/default copied
      template:
        src: templates/default.minio.j2
        dest: /etc/default/minio
        owner: minio
        group: minio
        mode: 0640
      notify: restart minio

    - name: be sure service file copied
      template:
        src: templates/minio.service.j2
        dest: /etc/systemd/system/minio.service
        owner: root
        group: root
        mode: 0644
      notify: restart minio

    - name: be sure service setup
      service:
        name: minio
        state: started
        enabled: yes

#
# nginx get facts
#
- name: get facts#
  block:
    - name: gets fact of private key
      stat:
        path: /etc/nginx/ssl/{{ nginx_fqdn }}.key
      register: fqdn_private_key

    - name: gets fact of public key
      stat:
        path: /etc/nginx/ssl/{{ nginx_fqdn }}.crt
      register: fqdn_public_key

#
# nginx reverse proxy
#
- name: nginx reverse proxy 
  block:
    - name: be sure nginx installed
      apt:
        name: nginx

    - name: be sure nginx ssl directory created
      file:
        path: /etc/nginx/ssl
        state: directory
        mode: 0755

    - name: be sure SSL server private key created
      command: openssl genrsa -out /etc/nginx/ssl/{{nginx_fqdn}}.key 2048
      when: fqdn_private_key.stat.exists == false

    - name: be sure SSL server public key created
      command: openssl req -new -x509 -days 3650 -key /etc/nginx/ssl/{{ nginx_fqdn }}.key -out /etc/nginx/ssl/{{ nginx_fqdn }}.crt -subj "/C=JP/ST=Tokyo/L=Chiyoda-ku/O=organization/CN=<{{ nginx_fqdn }}>"
      when: fqdn_public_key.stat.exists == false


    - name: be sure default configuration deleted
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: restart nginx

    - name: be sure nginx configuration for minio
      template:
        src: templates/nginx/minio-reverse-proxy.j2
        dest: /etc/nginx/sites-enabled/minio-reverse-proxy
        mode: 0644
      notify: restart nginx


  when: use_nginx_reverse_proxy
